import type { Movie } from "../types/movie";

export const mockMovies: Movie[] = [
  {
    id: "1",
    title: "The Shawshank Redemption",
    poster: "https://placehold.co/300x450?text=The+Shawshank+Redemption",
    releaseDate: "1994-09-23",
    plot: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
    director: "Frank Darabont",
    genres: ["Drama"],
    rating: 9.3,
    duration: "142 min",
  },
  {
    id: "2",
    title: "The Godfather",
    poster: "https://placehold.co/300x450?text=The+Godfather",
    releaseDate: "1972-03-24",
    plot: "An aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    cast: ["Marlon Brando", "Al Pacino", "James Caan", "Diane Keaton"],
    director: "Francis Ford Coppola",
    genres: ["Crime", "Drama"],
    rating: 9.2,
    duration: "175 min",
  },
  {
    id: "3",
    title: "The Dark Knight",
    poster: "https://placehold.co/300x450?text=The+Dark+Knight",
    releaseDate: "2008-07-18",
    plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests.",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
    director: "Christopher Nolan",
    genres: ["Action", "Crime", "Drama"],
    rating: 9.0,
    duration: "152 min",
  },
  {
    id: "4",
    title: "Pulp Fiction",
    poster: "https://placehold.co/300x450?text=Pulp+Fiction",
    releaseDate: "1994-10-14",
    plot: "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
    director: "Quentin Tarantino",
    genres: ["Crime", "Drama"],
    rating: 8.9,
    duration: "154 min",
  },
  {
    id: "5",
    title: "Inception",
    poster: "https://placehold.co/300x450?text=Inception",
    releaseDate: "2010-07-16",
    plot: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    cast: ["Leonardo DiCaprio", "Marion Cotillard", "Tom Hardy", "Ellen Page"],
    director: "Christopher Nolan",
    genres: ["Action", "Sci-Fi", "Thriller"],
    rating: 8.8,
    duration: "148 min",
  },
  {
    id: "6",
    title: "Forrest Gump",
    poster: "https://placehold.co/300x450?text=Forrest+Gump",
    releaseDate: "1994-07-06",
    plot: "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man.",
    cast: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Sally Field"],
    director: "Robert Zemeckis",
    genres: ["Drama", "Romance"],
    rating: 8.8,
    duration: "142 min",
  },
  {
    id: "7",
    title: "The Matrix",
    poster: "https://placehold.co/300x450?text=The+Matrix",
    releaseDate: "1999-03-31",
    plot: "A computer programmer is led to fight an underground war against powerful computers who have constructed his entire reality with a system called the Matrix.",
    cast: [
      "Keanu Reeves",
      "Laurence Fishburne",
      "Carrie-Anne Moss",
      "Hugo Weaving",
    ],
    director: "Lana Wachowski, Lilly Wachowski",
    genres: ["Action", "Sci-Fi"],
    rating: 8.7,
    duration: "136 min",
  },
  {
    id: "8",
    title: "Goodfellas",
    poster: "https://placehold.co/300x450?text=Goodfellas",
    releaseDate: "1990-09-21",
    plot: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.",
    cast: ["Robert De Niro", "Ray Liotta", "Joe Pesci", "Lorraine Bracco"],
    director: "Martin Scorsese",
    genres: ["Biography", "Crime", "Drama"],
    rating: 8.7,
    duration: "146 min",
  },
  {
    id: "9",
    title: "Interstellar",
    poster: "https://placehold.co/300x450?text=Interstellar",
    releaseDate: "2014-11-07",
    plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    cast: [
      "Matthew McConaughey",
      "Anne Hathaway",
      "Jessica Chastain",
      "Michael Caine",
    ],
    director: "Christopher Nolan",
    genres: ["Adventure", "Drama", "Sci-Fi"],
    rating: 8.6,
    duration: "169 min",
  },
  {
    id: "10",
    title: "Parasite",
    poster: "https://placehold.co/300x450?text=Parasite",
    releaseDate: "2019-05-30",
    plot: "A poor family schemes to become employed by a wealthy family by infiltrating their household and posing as unrelated, highly qualified individuals.",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    director: "Bong Joon Ho",
    genres: ["Comedy", "Drama", "Thriller"],
    rating: 8.5,
    duration: "132 min",
  },
];
